// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

// PEM formatted file with additional certificates to trust for TLS connection
func GetAdditionalTrustCertsFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "solidserver:additionalTrustCertsFile")
}

// SOLIDServer API hostname or IP address
func GetHost(ctx *pulumi.Context) string {
	return config.Require(ctx, "solidserver:host")
}

// SOLIDServer API user's password
func GetPassword(ctx *pulumi.Context) string {
	return config.Require(ctx, "solidserver:password")
}

// Enable/Disable ssl verify (Default : enabled)
func GetSslverify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "solidserver:sslverify")
}

// SOLIDServer API user's ID
func GetUsername(ctx *pulumi.Context) string {
	return config.Require(ctx, "solidserver:username")
}
