# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class IPSubnet(pulumi.CustomResource):
    block: pulumi.Output[str]
    class_: pulumi.Output[str]
    class_parameters: pulumi.Output[dict]
    gateway: pulumi.Output[str]
    gateway_offset: pulumi.Output[int]
    name: pulumi.Output[str]
    prefix: pulumi.Output[str]
    size: pulumi.Output[int]
    space: pulumi.Output[str]
    terminal: pulumi.Output[bool]
    def __init__(__self__, resource_name, opts=None, block=None, class_=None, class_parameters=None, gateway_offset=None, name=None, size=None, space=None, terminal=None, __name__=None, __opts__=None):
        """
        Create a IPSubnet resource with the given unique name, props, and options.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if not resource_name:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(resource_name, str):
            raise TypeError('Expected resource name to be a string')
        if opts and not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        if block is None:
            raise TypeError('Missing required property block')
        __props__['block'] = block

        __props__['class_'] = class_

        __props__['class_parameters'] = class_parameters

        __props__['gateway_offset'] = gateway_offset

        if name is None:
            raise TypeError('Missing required property name')
        __props__['name'] = name

        if size is None:
            raise TypeError('Missing required property size')
        __props__['size'] = size

        if space is None:
            raise TypeError('Missing required property space')
        __props__['space'] = space

        __props__['terminal'] = terminal

        __props__['gateway'] = None
        __props__['prefix'] = None

        super(IPSubnet, __self__).__init__(
            'solidserver:index/iPSubnet:IPSubnet',
            resource_name,
            __props__,
            opts)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

