# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "additional_trust_certs_file": "additionalTrustCertsFile",
    "class_": "class",
    "class_parameters": "classParameters",
    "gateway_offset": "gatewayOffset",
    "request_id": "requestId",
    "request_ip": "requestIp",
    "vlan_domain": "vlanDomain",
    "vlan_id": "vlanId",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "additionalTrustCertsFile": "additional_trust_certs_file",
    "class": "class_",
    "classParameters": "class_parameters",
    "gatewayOffset": "gateway_offset",
    "requestId": "request_id",
    "requestIp": "request_ip",
    "vlanDomain": "vlan_domain",
    "vlanId": "vlan_id",
}
