// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package solidserver

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type Device struct {
	s *pulumi.ResourceState
}

// NewDevice registers a new resource with the given unique name, arguments, and options.
func NewDevice(ctx *pulumi.Context,
	name string, args *DeviceArgs, opts ...pulumi.ResourceOpt) (*Device, error) {
	if args == nil || args.Name == nil {
		return nil, errors.New("missing required argument 'Name'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["class"] = nil
		inputs["classParameters"] = nil
		inputs["name"] = nil
	} else {
		inputs["class"] = args.Class
		inputs["classParameters"] = args.ClassParameters
		inputs["name"] = args.Name
	}
	s, err := ctx.RegisterResource("solidserver:index/device:Device", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Device{s: s}, nil
}

// GetDevice gets an existing Device resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDevice(ctx *pulumi.Context,
	name string, id pulumi.ID, state *DeviceState, opts ...pulumi.ResourceOpt) (*Device, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["class"] = state.Class
		inputs["classParameters"] = state.ClassParameters
		inputs["name"] = state.Name
	}
	s, err := ctx.ReadResource("solidserver:index/device:Device", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Device{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *Device) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Device) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// The class associated to the device.
func (r *Device) Class() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["class"])
}

// The class parameters associated to device.
func (r *Device) ClassParameters() *pulumi.MapOutput {
	return (*pulumi.MapOutput)(r.s.State["classParameters"])
}

// The name of the device to create.
func (r *Device) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// Input properties used for looking up and filtering Device resources.
type DeviceState struct {
	// The class associated to the device.
	Class interface{}
	// The class parameters associated to device.
	ClassParameters interface{}
	// The name of the device to create.
	Name interface{}
}

// The set of arguments for constructing a Device resource.
type DeviceArgs struct {
	// The class associated to the device.
	Class interface{}
	// The class parameters associated to device.
	ClassParameters interface{}
	// The name of the device to create.
	Name interface{}
}
