// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("solidserver");

/**
 * PEM formatted file with additional certificates to trust for TLS connection
 */
export let additionalTrustCertsFile: string | undefined = __config.get("additionalTrustCertsFile");
/**
 * SOLIDServer API hostname or IP address
 */
export let host: string = __config.require("host");
/**
 * SOLIDServer API user's password
 */
export let password: string = __config.require("password");
/**
 * Enable/Disable ssl verify (Default : enabled)
 */
export let sslverify: boolean | undefined = __config.getObject<boolean>("sslverify");
/**
 * SOLIDServer API user's ID
 */
export let username: string = __config.require("username");
